# Generated by Django 4.2.29 on 2026-03-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_studentsessionstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="session_audio/"),
        ),
    ]
