# Generated by Django 4.2.29 on 2026-03-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_role_studentdiary_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="animation_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="asset",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="assets/"),
        ),
    ]
