# Generated by Django 4.2.29 on 2026-04-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_asset_animation_config_alter_asset_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="game_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="session",
            name="game_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="mode",
            field=models.CharField(
                choices=[("freedom", "Freedom Canvas"), ("game", "Game Creation")],
                default="freedom",
                max_length=20,
            ),
        ),
    ]
