# Generated by Django 4.2 on 2026-05-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_session_game_config_session_game_type_session_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="game_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("puzzle", "Puzzle"),
                    ("trivia", "Trivia"),
                    ("math", "Math"),
                    ("physics", "Physics"),
                    ("color", "Color Mix"),
                    ("chemistry", "Chemistry"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
