# Generated by Django 4.2.30 on 2026-07-01 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_session_game_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("trivia", "Trivia"),
                            ("puzzle", "Puzzle"),
                            ("math", "Math"),
                            ("physics", "Physics"),
                            ("color", "Color Mix"),
                            ("chemistry", "Chemistry"),
                        ],
                        max_length=50,
                    ),
                ),
                ("game_config", models.JSONField(blank=True, default=dict)),
                ("is_public", models.BooleanField(default=False)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        limit_choices_to={"role": "mentor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
