# Generated by Django 4.2.30 on 2026-07-01 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_session_game_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="trophy", max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("courses", "Course Completion"),
                            ("sessions", "Session Participation"),
                            ("diaries", "Diary Creation"),
                            ("games", "Game Performance"),
                            ("engagement", "User Engagement"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "requirement_value",
                    models.IntegerField(help_text="Required count to earn achievement"),
                ),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("courses_completed", "Courses Completed"),
                            ("sessions_completed", "Sessions Completed"),
                            ("diaries_created", "Diaries Created"),
                            ("games_won", "Games Won"),
                            ("games_played", "Games Played"),
                            ("perfect_scores", "Perfect Scores"),
                            ("consecutive_days", "Consecutive Days Active"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        default=10, help_text="Points awarded when earned"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
