# Generated by Django 4.2.30 on 2026-07-01 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_user_streak"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light (Default)"),
                            ("high-contrast", "High Contrast"),
                        ],
                        default="light",
                        max_length=20,
                    ),
                ),
                (
                    "colorblind_mode",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("protanopia", "Protanopia (Red-blind)"),
                            ("deuteranopia", "Deuteranopia (Green-blind)"),
                            ("tritanopia", "Tritanopia (Blue-blind)"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("reduced_motion", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
