# Generated by Django 4.2.30 on 2026-07-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="dyslexic_font",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="font_size",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("large", "Large"),
                    ("x-large", "Extra Large"),
                ],
                default="normal",
                max_length=10,
            ),
        ),
    ]
