# Generated by Django 4.2.30 on 2026-07-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_dyslexia_font_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="game_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("puzzle", "Puzzle"),
                    ("trivia", "Trivia"),
                    ("math", "Math"),
                    ("physics", "Physics"),
                    ("color", "Color Mix"),
                    ("chemistry", "Chemistry"),
                    ("memory", "Memory Match"),
                    ("maze", "Maze"),
                    ("word_scramble", "Word Scramble"),
                    ("flashcard", "Flashcard"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sessiontemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("trivia", "Trivia"),
                    ("puzzle", "Puzzle"),
                    ("math", "Math"),
                    ("physics", "Physics"),
                    ("color", "Color Mix"),
                    ("chemistry", "Chemistry"),
                    ("memory", "Memory Match"),
                    ("maze", "Maze"),
                    ("word_scramble", "Word Scramble"),
                    ("flashcard", "Flashcard"),
                ],
                max_length=50,
            ),
        ),
    ]
