# Generated by Django 4.2.30 on 2026-07-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_session_game_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("recorded", "Recorded Lesson"),
                    ("live", "Live Collaboration"),
                ],
                default="recorded",
                max_length=20,
            ),
        ),
    ]
