# Generated by Django 4.2.30 on 2026-07-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_user_is_verified_parentstudentlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="A short biography or description of the user",
                null=True,
            ),
        ),
    ]
