# Generated by Django 4.2.30 on 2026-07-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="User profile picture",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
