# Generated by Django 4.2.30 on 2026-07-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_classgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="usage_count",
            field=models.IntegerField(default=0),
        ),
    ]
