# Generated by Django 6.0.7 on 2026-07-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_asset_usage_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="tier",
            field=models.CharField(
                choices=[("bronze", "Bronze"), ("silver", "Silver"), ("gold", "Gold")],
                default="bronze",
                help_text="Achievement difficulty tier",
                max_length=10,
            ),
        ),
    ]
